mozilla/telemetry-analysis-service

atmo/templates/atmo/delete-cluster.jinja, atmo/templates/atmo/edit-cluster.jinja, atmo/templates/atmo/new-cluster.jinja, atmo/templates/atmo/new-worker.jinja, atmo/workers/urls.py
Some of the forms were using outdated static urls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/10)
=> Bug 1296573 - fix form urls in jinja templates

atmo/utils/provisioning.py
When this flag is not set to True and using IAM roles, the clusters (as far as I can tell) become orphaned and are not visible or able to be terminated by anyone except the AWS account holder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/11)
=> Set "VisibleToAllUsers" to True in cluster_start

docker-compose.yml, requirements.txt
My fork of rq-scheduler supports running multiple schedulers
side-by-side. Once my patch gets merged we can point the requirements
back to the upstream version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/17)
=> Bug 1303104 - Use forked version of rq-scheduler

atmo/jobs/models.py, atmo/jobs/tests.py, atmo/workers/models.py
Also added a bunch of tests for the logic in `should_run`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/22)
=> Bug 1307087 - Fix SparkJob.should_run when a job has no expiration

atmo/clusters/models.py, atmo/clusters/tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/23)
=> Bug 1307184 - Correctly handle unset public cluster IPs during save

atmo/jobs/models.py, atmo/jobs/urls.py, atmo/jobs/views.py, atmo/templates/atmo/dashboard.html, atmo/templates/atmo/detail-cluster.html, atmo/templates/atmo/detail-spark-job.html, atmo/utils/scheduling.py
This also fixes a few bugs in the spark job startup code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/35)
=> Bug 1308712 - Add Spark job detail view

atmo/static/js/base.js, atmo/static/js/refresher.js, atmo/templates/atmo/base.html, atmo/templates/atmo/cluster-detail.html
This also shows a tooltip for the timedelta and the current UTC time as a tooltip over the time in the footer
=> Bug 1311457 - Show termination time in cluster detail page instead of timedelta

atmo/clusters/forms.py, atmo/forms/fields.py, atmo/forms/mixins.py, atmo/jobs/forms.py
This also uses django.forms.models.ModelForm as the
base class of the mixin to have a consistent bases for
our forms.
=> Factor confirmation form into own mixin

atmo/settings.py
Add a CSP report endpoint that will be handled in nginx.
In dev, this will send to an endpoint that 404s so it could be moved in to stage/prod specific config.
=> Bug 1319545 - Add CSP report URI to settings

circle.yml
The CircleCi build is failing because is missing a apt-get update
=> Fix CircleCi builds

atmo/worker.py, bin/run
=> Close database connections on startup of the worker, before and after each job.

atmo/templates/atmo/jobs/detail.html
AWS returns these in lexicographical order. These are named following a
pattern of <identifier>/logs/<identifier>.<YYYYMMDDHHMMSS>.log.gz so by
default they would be ordered by date.
=> Fix #207: Reverse log display order

Dockerfile.dev, bin/test
This basically makes sure the `wait_for` function in the `bin/run` is properly used in development. We already set the `DEVELOPMENT` env var when running tests via `bin/test` but it seems as if this was mistakenly missed in setting it for when we just start the server via `make up` etc. Since we're using an own Dockerfile for development (`Dockerfile.dev`) we can easily set it there and don't have to think about it much.
=> Fix #407 - Make sure we always run in dev mode so we wait for database and redis.

.gitignore, atmo/settings.py, bin/run, docker-compose.yml, requirements.txt
For the record, [django_celery_monitor](https://pypi.python.org/pypi/django_celery_monitor) is a port of the monitoring feature in the old django-celery app and I released it on PyPI: https://pypi.python.org/pypi/django_celery_monitor
=> Use django_celery_monitor to be able to inspect Celery tasks and workers in realtime.

atmo/celery.py, atmo/settings.py, bin/run, requirements.txt
This uses a fix for redbeat’s distributed Redis lock.
Removing some of the custom setting fixes we had to do as well.
Fix #417.
=> Make sure the scheduler will only ever run run as a singleton.

atmo/settings.py, atmo/templates/atmo/_announcements.html, atmo/templates/atmo/base.html, atmo/templatetags.py
This uses the existing Constance config app in the admin to render optionally a Markdown announcement.
This also adds admin fieldsets to the Constance config page.
=> Fix #420 - Add ability to render announcements.

atmo/templates/atmo/clusters/detail.html
=> Fix #460: Add Zeppelin examples to cluster detail

atmo/clusters/forms.py, atmo/clusters/queries.py, tests/clusters/test_forms.py
This also changes the labels from using simple text and parens to using bootstrap labels for deprecated and experimental EMR releases.
Example:
=> Fix #550: Filter out inactive EMR releases

atmo/templates/atmo/jobs/mails/failed_run_alert.mail
Not sure if I should add the description to the title of the mail as well; I think having it in the body is good enough.
=> added description of spark job to failed run alert email

docker-compose.yml
The depends_on directive is needed if one service depends on another,
it is not needed if one service is simply based on another's definition.
https://docs.docker.com/compose/compose-file/#depends_on
=> Remove unnecessary "depends_on" directives in docker compose config

atmo/clusters/provisioners.py, atmo/jobs/provisioners.py, atmo/provisioners.py, atmo/settings.py, tests/clusters/test_provisioners.py, tests/jobs/test_provisioners.py
I saw that jezdez is wanting to move away from env vars, so I'm moving these to constance.
=> Move AWS configs from env vars to constance

atmo/templates/atmo/base.html
This replaces the wiki link in the footer with the gitbook link the wiki redirects users towards.
=> save a redirect

atmo/jobs/models.py, tests/jobs/test_models.py
This code incorrectly assumed that `ready_at` will exist if
`finished_at` exists, which is not true when we have a bootstrap
termination with errors.
=> Fix #802: Add checking around metrics

.pyup.yml, requirements/build.txt
This makes things a bit quieter since we have a few high maintenance dependencies (e.g. boto/botocore).
=> Some pyup.io fixes.

atmo/settings.py, atmo/users/backends.py
Disabled by default as it requires deployment changes.
Fix #978.
=> Extend the OIDC authentication backend with the ability to verify remote user groups against a configured list of allowed user groups.
