analysis_service/settings.py, analysis_service/wsgi.py, bin/run-dev.sh, docker-compose.yml, requirements.txt
See individual commits for details
=> Various changes to the dev environment setup

circle.yml
This is part of the work for continuous delivery.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/6)
=> Add circle config for build + push to dockerhub

circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/8)
=> Bug 1291697 - properly run tests on CircleCI

.travis.yml, Dockerfile, atmo/settings.py, atmo/urls.py, docker-compose-base.yml, docker-compose.yml, requirements.txt, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/13)
=> Bug 1301048 - Setup RQ worker and scheduler

atmo/templates/atmo/new-cluster.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/19)
=> Bug 1303687 - fix TemplateSyntaxError. Fix #18

atmo/static/css/base.css, atmo/static/css/dashboard.css, atmo/templates/account/login.html, atmo/templates/atmo/base.html
Also make some minor style updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/25)
=> Add warning about stability

Procfile, atmo/clusters/jobs.py, atmo/jobs/jobs.py, atmo/settings.py, atmo/utils/middleware.py, atmo/workers/jobs.py, docker-compose.yml, newrelic.ini
This means the RQ jobs are instrumented with NewRelic by using RQ's SimpleWorker class that doesn't fork a new process per job but does the job performing inline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/31)
=> Bug 1308713 - Instrument RQ jobs

atmo/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/33)
=> Require encrypted connections to Postgres

atmo/settings.py
We need to do this because Boto doesn't know about our .env file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/32)
=> Populate the environment with AWS credentials

.buildpacks, Procfile, README.md
This also adds the use of the Heroku Multi Buildpack which installs multiple buildpacks as defined in `.buildpacks` (in order)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/34)
=> Secure Redis via SSL

atmo/settings.py, atmo/utils/provisioning.py
@jezdez r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/41)
=> Bug 1309901 - Use spot instances for ad-hoc clusters

atmo/templates/atmo/spark-job-detail.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/44)
=> Bug 1309569 - don't show job end date if it never ends

atmo/provisioning.py, atmo/settings.py
@jezdez or @maurodoglio r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/43)
=> Bug 1309901 - Add config for using spots or on demand instances

atmo/static/js/jobs.js, atmo/static/js/refresher.js, atmo/templates/atmo/base.html, atmo/templates/atmo/cluster-detail.html, atmo/templates/atmo/dashboard.html, atmo/templates/atmo/spark-job-detail.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/46)
=> Bug 1309597 - Add periodic page refresh for dashboard, cluster and job detail pages

atmo/clusters/forms.py, atmo/jobs/forms.py, atmo/static/js/forms.js, atmo/templates/atmo/_form.html, atmo/templates/atmo/cluster-detail.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/49)
=> Bug 1311387 - Render file inputs nicely

atmo/clusters/admin.py, atmo/jobs/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/51)
=> Bug 1311760 - Add custom admin site for Cluster and SparkJob

atmo/scheduling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/52)
=> Bug 1307087 - Stop hiding Spark job clusters from all IAM users

atmo/clusters/forms.py, atmo/jobs/forms.py, atmo/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/54)
=> Bug 1311781 - Increase maximum cluster size to 30

atmo/jobs/models.py, atmo/scheduling.py
This also fixes an issue with the last_run_date non getting updated
=> Bug 1307087 - Use full notebook uri for scheduling

atmo/jobs/models.py, tests/test_jobs.py
No jobs should be deleted without their owner's consent.
This patch also fixes a couple of issues with the expiration logic,
namely:
- the last_run_date vs timeout check was wrong
- only RUNNING jobs should be terminated because of a timeout
=> Bug 1313008 - Don't delete expired jobs

atmo/provisioning.py, atmo/scheduling.py, atmo/settings.py
I updated @fbertsch code and rebased it on top of latest master.
=> Bug 1307528 - Backup log files to s3

atmo/settings.py, atmo/static/js/raven.js, atmo/templates/atmo/base.html
Also remove unsafe-inline from CSP script-src setting
=> Bug 1315303 - Move RavenJS initialization into own file

.gitignore, Makefile, README.md, atmo/__init__.py, atmo/apps.py, atmo/context_processors.py, atmo/health/__init__.py, atmo/health/checks.py, atmo/health/urls.py, atmo/health/views.py, atmo/settings.py, atmo/urls.py, bin/post_compile, bin/pre_deploy, circle.yml
Many thanks to @mythmon for the inspiration in the Normandy code.
This also removes the need for Newrelic deploys to Heroku.
=> Bug 1316278 - Implement Dockerflow health checks

atmo/clusters/forms.py, atmo/jobs/forms.py, atmo/static/css/base.css, atmo/static/js/forms.js, atmo/templates/atmo/_form.html, atmo/templates/atmo/cluster-new.html, atmo/templates/atmo/spark-job-edit.html, atmo/templates/atmo/spark-job-new.html
=> Bug 1318319 - Show current time when creating jobs for start and end time

atmo/templates/atmo/dashboard.html, atmo/views.py
=> Bug 1316048 - Show Spark jobs in descending order on dashboard

atmo/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-analysis-service/91)
=> Bug 1319545 - Only report CSP violations in stage and prod.

README.md, atmo/clusters/provisioners.py, atmo/jobs/provisioners.py, atmo/provisioners.py, tests/test_provisioners.py
See mozilla/emr-bootstrap-spark#59.
=> Add Zeppelin support to on-demand clusters

atmo/jobs/forms.py, atmo/jobs/migrations/0012_add_job_run_history.py, atmo/jobs/views.py, atmo/templates/atmo/base.html
This is the result of QA I did on the latest tag https://github.com/mozilla/telemetry-analysis-service/tree/2017.2.8
=> Fixes for the Python 3 move, file input revamps and spark job runs.

atmo/jobs/jobs.py, atmo/jobs/models.py, bin/run, docker-compose.yml
This should fix a lot of the throttling issues since we do less API queries. Fix #284.
=> Use ListCluster EMR API to update last job runs statuses.

atmo/settings.py
=> Add redbeat logger.

atmo/celery.py, atmo/clusters/tasks.py, atmo/jobs/tasks.py, atmo/settings.py, tests/test_tasks.py
=> Refactor autoretrying as separate decorator and use it with ClientError.

atmo/clusters/factories.py, atmo/jobs/factories.py, atmo/keys/factories.py, atmo/users/factories.py, requirements.txt, tests/conftest.py, tests/test_clusters.py, tests/test_dashboard.py, tests/test_jobs.py, tests/test_keys.py, tests/test_provisioners.py
This uses factory_boy and pytest-factoryboy for easier text fixtures.
Fix #331.
=> Use factory_boy for text fixtures.

atmo/clusters/tasks.py
Fixes #434 by beginning the transaction earlier in the task and using `select_for_update()` on the expiring clusters, locking the rows for the duration of the transaction.
This may cause a problem of blocking requests that write to the cluster object for the duration of the task if there are many clusters that need to be expired at once -- if we ever run into that problem, we can consider a few different options (keep the SES connection open, fanout to separate expiration tasks for each expiring cluster, etc.)
Gave some thought to test and unless there's a public Django api that allows checking of an object's lock status, I can't think of a way to write one that's not a huge hack/non-deterministic.
=> Fix cluster expiration email race condition

atmo/templates/atmo/clusters/detail.html
=> Add cluster size to detail page.

atmo/settings.py, requirements.txt
=> Add responsive admin theme.

atmo/clusters/factories.py, atmo/clusters/forms.py, atmo/clusters/models.py, atmo/clusters/provisioners.py, atmo/clusters/views.py, atmo/jobs/factories.py, atmo/jobs/forms.py, atmo/jobs/models.py, atmo/jobs/provisioners.py, atmo/jobs/views.py, atmo/names.py, atmo/provisioners.py, setup.cfg, tests/clusters/test_provisioners.py, tests/clusters/test_views.py, tests/jobs/test_provisioners.py, tests/jobs/test_views.py, tests/test_names.py
=> Use better unique identifiers for Spark jobs and clusters.

atmo/jobs/tasks.py
I looked at each of the list of tasks listed in #454 and it appears that all but one of these shouldn't have adverse effects if run twice/simultaneously -- I think in those cases it probably makes sense to just allow it to happen instead of locking those rows in the database, increasing the possibility of contention. Let me know if you think otherwise and I'm happy to update the rest of the tasks.
=> Use select_for_update to prevent race condition in send_run_alert_mails

atmo/jobs/models.py, atmo/templates/atmo/jobs/detail.html
=> Fix #271: Add job history details

package.json
=> fix(package): update clipboard to version 1.7.1

.gitignore, Dockerfile, Dockerfile.dev, package-lock.json
=> Fix #532 - Use Node 5 to get package integrity checks and a lockfile.

atmo/settings.py
Bootstrap side change:
https://github.com/mozilla/emr-bootstrap-spark/pull/94
=> Fix #584: Allow bootstrap bucket to be configurable

atmo/news/views.py
As per https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies
=> Added secure and http_only cookie flags

atmo/clusters/views.py, atmo/static/js/clusters.js, atmo/templates/atmo/clusters/detail.html
Not sure if these needs tests since it's chiefly a doc change.
=> Instructions for mounting EFS locally (re #557)

package.json
=> fix(package): update raven-js to version 3.22.1

package.json
=> fix(package): update raven-js to version 3.23.1

requirements/build.txt
This is a security bugfix: https://www.djangoproject.com/weblog/2018/mar/06/security-releases/
=> Updated Django to 1.11.11.

atmo/templates/atmo/clusters/detail.html
This documentation has moved to the unified telemetry docs
=> Update link to custom analysis with spark

atmo/settings.py, requirements/build.txt
=> Support SameSite cookie attribute on sessionid.
